<?php

$produtos = array(
    0 => array('nome'=>'#5634', 'preco'=>'15.200.360.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'5634.jpg'),
    1 => array('nome'=>'Cachorro Legal', 'preco'=>'1500.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'9607.jpg'),
    2 => array('nome'=>'Capivara Legal', 'preco'=>'900.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'7638.jpg'),
    3 => array('nome'=>'Girafa Legal', 'preco'=>'700.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'girafa_legal.jpg'),
    4 => array('nome'=>'Macaco Legal', 'preco'=>'1400.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'macaco_legal.jpg'),
    5 => array('nome'=>'Gato Legal', 'preco'=>'600.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'gato_legal.jpg'),
    6 => array('nome'=>'Rato Legal', 'preco'=>'600.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'rato_legal.jpg'),
    7 => array('nome'=>'Jacaré Legal', 'preco'=>'1500.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'jacare_legal.jpg'),
    8 => array('nome'=>'Passarinho Legal', 'preco'=>'600.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'passarinho_legal.jpg'),
    9 => array('nome'=>'Leão Legal', 'preco'=>'1500.00','descricao'=>'By Bored Ape Yacht Club', 'imagem'=>'leao_legal.jpg'),
    10 => array('nome'=>'Tucano Legal', 'preco'=>'600.00','descricao'=>'Descrição Tucano Legal', 'imagem'=>'tucano_legal.jpg'),
    11 => array('nome'=>'Golfinho Legal', 'preco'=>'1200.00','descricao'=>'Descrição Golfinho Legal', 'imagem'=>'golfinho_legal.jpg'),
    12 => array('nome'=>'Onça Legal', 'preco'=>'1500.00','descricao'=>'Descrição Onça Legal', 'imagem'=>'onca_legal.jpg'),
    13 => array('nome'=>'Coruja Legal', 'preco'=>'900.00','descricao'=>'Descrição Coruja Legal', 'imagem'=>'coruja_legal.jpg'),
    14 => array('nome'=>'Cobra Legal', 'preco'=>'900.00','descricao'=>'Descrição Cobra Legal', 'imagem'=>'cobra_legal.jpg'),
    15 => array('nome'=>'Tatu Legal', 'preco'=>'600.00','descricao'=>'Descrição Tatu Legal', 'imagem'=>'tatu_legal.jpg'),
    16 => array('nome'=>'Pavão Legal', 'preco'=>'900.00','descricao'=>'Descrição Pavão Legal', 'imagem'=>'pavao_legal.jpg'),
    17 => array('nome'=>'Cabra Legal', 'preco'=>'1200.00','descricao'=>'Descrição Cabra Legal', 'imagem'=>'cabra_legal.jpg'),
    18 => array('nome'=>'Panda Legal', 'preco'=>'1500.00','descricao'=>'Descrição Panda Legal', 'imagem'=>'panda_legal.jpg'),
    19 => array('nome'=>'Papagaio Legal', 'preco'=>'1200.00','descricao'=>'Descrição Papagaio Legal', 'imagem'=>'papagaio_legal.jpg'),
    20 => array('nome'=>'Tartaruga Legal', 'preco'=>'600.00','descricao'=>'Descrição Tartaruga Legal', 'imagem'=>'tartaruga_legal.jpg'),
    21 => array('nome'=>'Coelho Legal', 'preco'=>'900.00','descricao'=>'Descrição Coelho Legal', 'imagem'=>'coelho_legal.jpg'),
    22 => array('nome'=>'Águia Legal', 'preco'=>'1500.00','descricao'=>'Descrição Águia Legal', 'imagem'=>'aguia_legal.jpg'),
    23 => array('nome'=>'Raposa Legal', 'preco'=>'1200.00','descricao'=>'Descrição Raposa Legal', 'imagem'=>'raposa_legal.jpg'),
    24 => array('nome'=>'Zebra Legal', 'preco'=>'1200.00','descricao'=>'Descrição Zebra Legal', 'imagem'=>'zebra_legal.jpg'),
    25 => array('nome'=>'Canguru Legal', 'preco'=>'900.00','descricao'=>'Descrição Canguru Legal', 'imagem'=>'canguru_legal.jpg'),
    26 => array('nome'=>'Pinguim Legal', 'preco'=>'1200.00','descricao'=>'Descrição Pinguim Legal', 'imagem'=>'pinguim_legal.jpg'),
    27 => array('nome'=>'Cavalo Legal', 'preco'=>'1500.00','descricao'=>'Descrição Cavalo Legal', 'imagem'=>'cavalo_legal.jpg'),
    28 => array('nome'=>'Rinoceronte Legal', 'preco'=>'1500.00','descricao'=>'Descrição Rinoceronte Legal', 'imagem'=>'rinoceronte_legal.jpg'),
    29 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    30 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    31 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    32 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    33 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    34 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    35 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    36 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    37 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    38 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    39 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    40 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    41 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    42 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    43 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    44 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    45 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    46 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    47 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    48 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    49 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    50 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    51 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    52 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    53 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    54 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    55 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    56 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    57 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    58 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    59 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg'),
    60 => array('nome'=>'Peixe Legal', 'preco'=>'1200.00','descricao'=>'Descrição Peixe Legal', 'imagem'=>'peixe_legal.jpg')
);
?>